level             = "elementary"
name              = "cube_sum"
tags              = ["math"]
time_to_solve_sec = 120

description_en = """
Calculate sum of cubes in array from $1$ to $n$.
"""

description_ru = """
Рассчитайте сумму кубов в массиве от $1$ до $n$.
"""

limits = """
- $1 \\leq n \\leq 100$
"""

solution = """
def solution(num: int) -> int:
    return sum(i ** 3 for i in range(1, num + 1))
"""

examples = """
solution(1) == 1
solution(2) == 9
solution(20) == 44100
solution(30) == 216225
"""

[[input_signature]]
argument_name = "num"
[input_signature.type]
name = "integer"

[output_signature.type]
name = "integer"

[[asserts]]
arguments = [1]
comment   = "Single cube"
expected  = 1

[[asserts]]
arguments = [2]
comment   = "Two cubes"
expected  = 9

[[asserts]]
arguments = [20]
comment   = "Twenty cubes"
expected  = 44100

[[asserts]]
arguments = [30]
comment   = "Thirty cubes"
expected  = 216225

[[asserts]]
arguments = [3]
comment   = "Three cubes"
expected  = 36

[[asserts]]
arguments = [4]
comment   = "Four cubes"
expected  = 100

[[asserts]]
arguments = [5]
comment   = "Five cubes"
expected  = 225

[[asserts]]
arguments = [6]
comment   = "Six cubes"
expected  = 441

[[asserts]]
arguments = [7]
comment   = "Seven cubes"
expected  = 784

[[asserts]]
arguments = [8]
comment   = "Eight cubes"
expected  = 1296

[[asserts]]
arguments = [9]
comment   = "Nine cubes"
expected  = 2025

[[asserts]]
arguments = [10]
comment   = "Ten cubes"
expected  = 3025

[[asserts]]
arguments = [11]
comment   = "Eleven cubes"
expected  = 4356

[[asserts]]
arguments = [12]
comment   = "Twelve cubes"
expected  = 6084

[[asserts]]
arguments = [13]
comment   = "Thirteen cubes"
expected  = 8281

[[asserts]]
arguments = [14]
comment   = "Fourteen cubes"
expected  = 11025

[[asserts]]
arguments = [15]
comment   = "Fifteen cubes"
expected  = 14400

[[asserts]]
arguments = [16]
comment   = "Sixteen cubes"
expected  = 18496

[[asserts]]
arguments = [17]
comment   = "Seventeen cubes"
expected  = 23409

[[asserts]]
arguments = [18]
comment   = "Eighteen cubes"
expected  = 29241

[[asserts]]
arguments = [19]
comment   = "Nineteen cubes"
expected  = 36100

[[asserts]]
arguments = [21]
comment   = "Twenty one cubes"
expected  = 53361

[[asserts]]
arguments = [22]
comment   = "Twenty two cubes"
expected  = 64009

[[asserts]]
arguments = [23]
comment   = "Twenty three cubes"
expected  = 76176

[[asserts]]
arguments = [24]
comment   = "Twenty four cubes"
expected  = 90000

[[asserts]]
arguments = [25]
comment   = "Twenty five cubes"
expected  = 105625

[[asserts]]
arguments = [40]
comment   = "Forty cubes"
expected  = 672400

[[asserts]]
arguments = [50]
comment   = "Fifty cubes"
expected  = 1625625

[[asserts]]
arguments = [60]
comment   = "Sixty cubes"
expected  = 3348900

[[asserts]]
arguments = [100]
comment   = "One hundred cubes"
expected  = 25502500
