level             = "elementary"
name              = "leap_year"
tags              = ["date-time"]
time_to_solve_sec = 150

description_en = """
Determine if the year is a leap year.

Leap years are all divisible by 4. But for Gregorian calendar, a year that is evenly divisible by 100 (for example, 1900) is a leap year only if it is also evenly divisible by 400.
"""

description_ru = """
Определите, является ли год високосным.

Любой год, который делится на 4 без остатка, является високосным годом. Тем не менее, есть еще небольшая особенность, которая должна быть учтена например, григорианский календарь предусматривает, что год, который делится без остатка на 100 является високосным годом только в том случае, если он также без остатка делится на 400.
"""

limits = """
- $1600 \\leq year \\leq 3000$
"""

solution = """
def solution(year: int) -> bool:
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)
"""

examples = """
solution(1804) == True
solution(2000) == True
solution(2012) == True
solution(2020) == True
solution(1913) == False
solution(2100) == False
"""

[[input_signature]]
argument_name = "year"
[input_signature.type]
name = "integer"

[output_signature.type]
name = "boolean"

[[asserts]]
arguments = [2012]
comment   = "Regular leap year divisible by 4"
expected  = true

[[asserts]]
arguments = [1913]
comment   = "Not divisible by 4"
expected  = false

[[asserts]]
arguments = [1804]
comment   = "Leap year in 19th century"
expected  = true

[[asserts]]
arguments = [2000]
comment   = "Divisible by 400"
expected  = true

[[asserts]]
arguments = [2100]
comment   = "Divisible by 100 but not 400"
expected  = false

[[asserts]]
arguments = [2020]
comment   = "Recent leap year"
expected  = true

[[asserts]]
arguments = [1900]
comment   = "Century not divisible by 400"
expected  = false

[[asserts]]
arguments = [2024]
comment   = "Leap year"
expected  = true

[[asserts]]
arguments = [2023]
comment   = "Not leap year"
expected  = false

[[asserts]]
arguments = [2400]
comment   = "Future leap year divisible by 400"
expected  = true

[[asserts]]
arguments = [1600]
comment   = "Historical leap year"
expected  = true

[[asserts]]
arguments = [1700]
comment   = "Century not leap"
expected  = false

[[asserts]]
arguments = [1800]
comment   = "Another century not leap"
expected  = false

[[asserts]]
arguments = [2004]
comment   = "Olympic year leap"
expected  = true

[[asserts]]
arguments = [2008]
comment   = "Olympic year leap"
expected  = true

[[asserts]]
arguments = [2016]
comment   = "Olympic year leap"
expected  = true

[[asserts]]
arguments = [2001]
comment   = "21st century start not leap"
expected  = false

[[asserts]]
arguments = [2002]
comment   = "Not divisible by 4"
expected  = false

[[asserts]]
arguments = [2003]
comment   = "Not divisible by 4"
expected  = false

[[asserts]]
arguments = [2028]
comment   = "Future leap year"
expected  = true

[[asserts]]
arguments = [2032]
comment   = "Future leap year"
expected  = true

[[asserts]]
arguments = [2200]
comment   = "Future century not leap"
expected  = false

[[asserts]]
arguments = [2300]
comment   = "Future century not leap"
expected  = false

[[asserts]]
arguments = [1996]
comment   = "Late 90s leap year"
expected  = true

[[asserts]]
arguments = [1992]
comment   = "Early 90s leap year"
expected  = true

[[asserts]]
arguments = [1988]
comment   = "Late 80s leap year"
expected  = true

[[asserts]]
arguments = [1984]
comment   = "Orwell year leap"
expected  = true

[[asserts]]
arguments = [1980]
comment   = "80s leap year"
expected  = true

[[asserts]]
arguments = [1976]
comment   = "US Bicentennial leap"
expected  = true

[[asserts]]
arguments = [1972]
comment   = "70s leap year"
expected  = true
