level             = "easy"
name              = "even_and_odd_all_way"
tags              = ["collections"]
time_to_solve_sec = 200

description_en = """
Given an array of numbers, return an array which contains all the odd numbers in the orginal array, which also have odd indexes, do the same for even numbers and indexes. If there is no such numbers, return `[0]`.
"""

description_ru = """
Дан массив чисел. Необходимо создать новый массив, содержащий нечетные числа с нечетными индексами, а также четные числа с четными индексами. В новом массиве числа должны сохранять исходный порядок. Если в исходном массиве не содержится чисел, удовлетворяющих этим условиям, верните `[0]`. Предполагается, что индексация массива начинается с нуля.
"""

solution = """
def solution(numbers):
    result = [num for i, num in enumerate(numbers)
              if (i % 2 == 0 and num % 2 == 0) or (i % 2 == 1 and num % 2 == 1)]
    return result if result else [0]
"""

examples = """
solution([1, 2, 3]) == [0]
solution([1, 3, 2, 5, 5]) == [3, 2, 5]
solution([0, 1, 2, 3, 4]) == [0, 1, 2, 3, 4]
"""

[[input_signature]]
argument_name = "numbers"
[input_signature.type]
name = "array"
[input_signature.type.nested]
name = "integer"

[output_signature.type]
name = "array"
[output_signature.type.nested]
name = "integer"

[[asserts]]
arguments = [[1, 2, 3]]
expected  = [0]

[[asserts]]
arguments = [[0, 1, 2, 3, 4]]
expected  = [0, 1, 2, 3, 4]

[[asserts]]
arguments = [[1, 3, 2, 5, 5]]
expected  = [3, 2, 5]

[[asserts]]
arguments = [[1, 2, 3, 3, 5, 6, 6]]
expected  = [3, 6]

[[asserts]]
arguments = [[1, 3, 1, 6, 9, 11, 13, 15, 16]]
expected  = [3, 11, 15, 16]

[[asserts]]
arguments = [[2, 2, 2, 2, 2]]
expected  = [2, 2, 2]

[[asserts]]
arguments = [[1, 1, 1, 1, 1]]
expected  = [1, 1]

[[asserts]]
arguments = [[0, 0, 0, 0]]
expected  = [0, 0]

[[asserts]]
arguments = [[10, 5, 20, 7, 30]]
expected  = [10, 5, 20, 7, 30]

[[asserts]]
arguments = [[1, 3, 5, 7, 9, 11]]
expected  = [3, 7, 11]

[[asserts]]
arguments = [[2, 4, 6, 8, 10, 12]]
expected  = [2, 6, 10]

[[asserts]]
arguments = [[100, 99, 200, 97, 300]]
expected  = [100, 99, 200, 97, 300]

[[asserts]]
arguments = [[-2, -3, -4, -5, -6]]
expected  = [-2, -3, -4, -5, -6]

[[asserts]]
arguments = [[0]]
expected  = [0]

[[asserts]]
arguments = [[1]]
expected  = [0]

[[asserts]]
arguments = [[5]]
expected  = [0]

[[asserts]]
arguments = [[4, 4, 4, 4, 4, 4]]
expected  = [4, 4, 4]

[[asserts]]
arguments = [[1, 2, 3, 4, 5, 6, 7, 8]]
expected  = [0]

[[asserts]]
arguments = [[0, 1, 2, 3, 4, 5, 6, 7]]
expected  = [0, 1, 2, 3, 4, 5, 6, 7]

[[asserts]]
arguments = [[11, 22, 33, 44, 55, 66]]
expected  = [0]

[[asserts]]
arguments = [[5, 10, 15, 20, 25, 30]]
expected  = [0]

[[asserts]]
arguments = [[-1, -2, -3, -4, -5]]
expected  = [0]

[[asserts]]
arguments = [[3, 6, 9, 12, 15]]
expected  = [0]

[[asserts]]
arguments = [[7, 14, 21, 28]]
expected  = [0]

[[asserts]]
arguments = [[8, 16, 24, 32, 40]]
expected  = [8, 24, 40]

[[asserts]]
arguments = [[1, 4, 2, 8, 3, 12]]
expected  = [2]

[[asserts]]
arguments = [[15, 30, 45, 60]]
expected  = [0]

[[asserts]]
arguments = [[9, 18, 27, 36, 45]]
expected  = [0]

[[asserts]]
arguments = [[50, 100, 150, 200, 250]]
expected  = [50, 150, 250]

[[asserts]]
arguments = [[2, 3, 4, 5, 6, 7, 8, 9, 10]]
expected  = [2, 3, 4, 5, 6, 7, 8, 9, 10]
