level             = "easy"
name              = "fixed_point_in_array"
tags              = ["collections"]
time_to_solve_sec = 300

description_en = """
Given an array of $n$ distinct integers sorted in ascending order, return a Fixed Point in the array, if there is a Fixed Point present in array; else return $-1$. Fixed Point in an array is an index $i$ such that $\\text{arr}[i]$ is equal to $i$.
"""

description_ru = """
Дан массив из $n$ различных целых чисел, упорядоченных по возрастанию. Верните фиксированную точку в данном массиве, если она присутствует в нём, иначе верните $-1$. Фиксированная точка в массиве $\\text{arr}$ - это индекс $i$, такой, что элемент $\\text{arr}[i]$ равен $i$. Предполагается, что индексация массива начинается с нуля.
"""

limits = """
- $1 \\leq \\text{len}(\\text{arr}) \\leq 100$
"""

solution = """
def solution(arr):
    for i, val in enumerate(arr):
        if i == val:
            return i
    return -1
"""

examples = """
solution([0, 2, 5, 8, 17]) == 0
solution([-10, -5, 0, 3, 7]) == 3
solution([-10, -5, 3, 4, 7, 9]) == -1
solution([-3, -2, -1, 3, 4, 7, 8]) == 3
"""

[[input_signature]]
argument_name = "arr"
[input_signature.type]
name = "array"
[input_signature.type.nested]
name = "integer"

[output_signature.type]
name = "integer"

[[asserts]]
arguments = [[-10, -5, 0, 3, 7]]
expected  = 3

[[asserts]]
arguments = [[0, 2, 5, 8, 17]]
expected  = 0

[[asserts]]
arguments = [[-10, -5, 3, 4, 7, 9]]
expected  = -1

[[asserts]]
arguments = [[-3, -2, -1, 3, 4, 7, 8]]
expected  = 3

[[asserts]]
arguments = [[1, 2, 3, 4, 5]]
expected  = -1

[[asserts]]
arguments = [[-5, -4, -3, -2, -1]]
expected  = -1

[[asserts]]
arguments = [[0]]
expected  = 0

[[asserts]]
arguments = [[1]]
expected  = -1

[[asserts]]
arguments = [[-1, 1]]
expected  = 1

[[asserts]]
arguments = [[0, 1, 2, 3, 4]]
expected  = 0

[[asserts]]
arguments = [[-10, -9, -8, 3]]
expected  = 3

[[asserts]]
arguments = [[5, 6, 7, 8, 9]]
expected  = -1

[[asserts]]
arguments = [[-3, -2, 2]]
expected  = 2

[[asserts]]
arguments = [[10, 11, 12, 13, 14]]
expected  = -1

[[asserts]]
arguments = [[-1, 0, 2]]
expected  = 2

[[asserts]]
arguments = [[0, 1]]
expected  = 0

[[asserts]]
arguments = [[-5, 1]]
expected  = 1

[[asserts]]
arguments = [[2, 3, 4, 5]]
expected  = -1

[[asserts]]
arguments = [[-10, -5, 2, 10]]
expected  = 2

[[asserts]]
arguments = [[0, 5, 10, 15]]
expected  = 0

[[asserts]]
arguments = [[-20, -10, -5, 3, 10]]
expected  = 3

[[asserts]]
arguments = [[1, 2, 3]]
expected  = -1

[[asserts]]
arguments = [[-1, -1, 2, 3]]
expected  = 2

[[asserts]]
arguments = [[7, 8, 9, 10]]
expected  = -1

[[asserts]]
arguments = [[-100, -50, 2, 50, 100]]
expected  = 2

[[asserts]]
arguments = [[0, 10, 20, 30]]
expected  = 0

[[asserts]]
arguments = [[-2, -1, 2, 3, 4, 5]]
expected  = 2

[[asserts]]
arguments = [[5]]
expected  = -1

[[asserts]]
arguments = [[-7, -6, -5, 3, 4]]
expected  = 3

[[asserts]]
arguments = [[1, 10, 100]]
expected  = -1
